import React,{ useState } from 'react';
import '/Applications/XAMPP/xamppfiles/htdocs/wastewise/wastewise/src/pages/css/Cp.css';
import {}from "react-router";
import '/Applications/XAMPP/xamppfiles/htdocs/wastewise/wastewise/src/pages/css/Cate.css'
import {Link} from "react-router-dom";
import axios from 'axios';
import elogo from'/Applications/XAMPP/xamppfiles/htdocs/wastewise/wastewise/src/pages/image/images-small-globe.svg';

function Cate() {

    
    return (

        <><div className="bg">
            <h1 className='name1'>Categories</h1>
          
            <a href='/'> <img className='img1' src={elogo} alt='logo1'/></a>
            <a className='pc1' href="/Dom">Domestic Waste</a>
            <p className='pc2' >Domestic waste is the waste material generated by households. 
            </p><p className='pc2'>This waste can be comprised of non-Hazardous Waste and hazardous waste.</p>
            <a className='pc1' href="/ind">Industrial Waste</a>
            <p className='pc2'>Industrial waste is the waste produced by industrial activity which includes </p>
            <p className='pc2'>any material that is rendered useless during a manufacturing process such as that of factories, mills, and mining operations.</p>
            <a className='pc1' href="/Comm">Commercial Waste</a>
            <p className='pc2'>Commercial waste consists of waste from premises used mainly for a trade or business or for sport,</p>
            <p className='pc2'>recreation, education or entertainment, but excluding household, agricultural or industrial waste.</p>
            <a className='pc1' href="/Health">HealthCare Waste</a>
            <p className='pc2'>Healthcare waste is all the waste generated by healthcare facilities, medical laboratories and </p>
            <p className='pc2'> biomedical research facilities, as well as waste from minor or scattered sources.</p>
            <a className='pc1' href="/Agri">Agriculture Waste</a>
            <p className='pc2'>Agricultural Waste is unwanted or unsalable materials produced wholly from agricultural operations directly related </p>
            <p className='pc2'>to growing crops or raising animals for the primary purpose of making a profit or for a livelihood.</p>

        </div><div>
              
            </div></>
        
    );
}

export default Cate;

